jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://mysql:3306
  username: root
  password: root

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  connection:
    driver_class: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://mysql:3306
